### ISSUE TITLE
The babel target doesn't work

### ISSUE THREAD

**Issue by glebm** [vishesh/racketscript#70] opened 2017-08-25 10:51 UTC
```
Error: Cannot find module 'babel-core'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/glebm/repos/glebm/waxeye/tmp/racks/node_modules/gulp-babel/index.js:7:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
[info] Finished.
```

This is probably because it's missing from `package.json`.

**Comment by vishesh** [comment] 2017-08-25 20:46
Confirmed on a clean machine. Seems like dependency of some other package changed which no longer installs this. I think I used this target 3-4 weeks ago and was working fine.

**Comment by glebm** [comment] 2017-08-26 09:41
Any reason why we support both babel and traceur?
Seems like nowadays we can just use babel

**Comment by vishesh** [comment] 2017-08-26 20:23
d7bb59fed1c9d03bdbdffdf7dabfaf2ba4ddb3aa fixes the issue for me. Please close this if it fixes for you as well.

I started with Traceur because it was dead simple to use. As opposed to Babel's n different configs and packages, Traceur was one single package. Later when I got some extra bandwidth I added Babel and Webpack. I also like the Traceur command line that can take ES6 files directly and compile-run on the fly.  Its quicker to debug the ES6 files directly than the compiled ones. I now see that Babel has `babel-node` as well. So you can say Traceur is here mostly for convenience than any technical reason.

**Comment by glebm** [comment] 2017-08-26 20:32
For babel nowadays it's as simple as using [babel-preset-env](https://github.com/babel/babel-preset-env#babel-preset-env----). Babel is more compatible, for example, `subclassObj instanceof SuperClass` [works](http://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-2&targets=&browsers=&builtIns=false&debug=false&experimental=false&loose=false&spec=false&playground=false&code_lz=MYGwhgzhAECC0G8C-AoUkYCFoFMAeALjgHYAmM8yaA9sRNSDgHQjUDmAFMTgO7SYcAlNACWdAmGLAc1AGZxBAbiA) in Babel.

Let's just drop traceur, so we don't have to work around its quirks?

**Comment by vishesh** [comment] 2017-08-26 21:01
I'm open to this idea to make Babel default target. We'll need to do following:

1. Support Babel target for tests #6. We also need to be careful about increasing test-run time e.g. maybe not combine all modules again and again but instead just load one module which would load others. This is anyway important, regardless we drop Traceur or not.
2. Make Playground work with Babel output. Right now, Playground asks server to compile to ES6 and Traceur does the rest at client-side on-the-fly. However, its not that important as we can just keep Traceur is "un-official" and "un-tested" target.

Regarding `instanceof` problem you mentioned, this code seems to do fine:

```javascript
class Foo {
}

class Bar extends Foo {
}

var x = new Foo();
var y = new Bar();

console.log(x instanceof Foo);
console.log(x instanceof Bar);
console.log(y instanceof Foo);
console.log(y instanceof Bar);
```

```
[14:00:02] vishesh@vy-xps » ~/tmp
  % node try.js 
true
false
true
true

[14:00:11] vishesh@vy-xps » ~/tmp
  % traceur try.js 
true
false
true
true
```

**Comment by vishesh** [comment] 2017-08-27 03:19
If Babel works for you, we can close this.

**Closed** 2017-08-27 10:31 UTC
