### ISSUE TITLE
Need something like `$/string-literal` to indicate native string literals

### ISSUE THREAD

**Issue by glebm** [vishesh/racketscript#81] opened 2017-08-28 17:11 UTC
With #75 `"string literals"` will compile to UStrings.
We still need the ability to specify regular string literals in RacketScript, e.g. to make `$/typeof` work

**Comment by vishesh** [comment] 2017-08-28 21:09
This along with your PR#75 brings the question on FFI interface. I doubt RacketScript will just be complete Racket programs, and will often use external JS libraries. Now for Arrays and Objects it make sense to have specific functions to manually convert them as they don't exist in both Racket and JS world. However, strings exist in both world, are commonly used, and manually converting them for interoperation b/w Racket and JS is not ideal situation.

Its probably possible to make flow from JavaScript to Racket to be seamless as we can simply have alternative representations for our runtime, while the other way flow will require manual conversions all the time. We don't have to worry about this in your PR, but its a point that we should think about. A verbose FFI is not ideal.

**Comment by glebm** [comment] 2017-08-28 21:23
Another thing to consider is that native JS libraries are hard to use directly due to much different interfaces (not just strings) and would likely require wrappers to be easy-to-use anyway.

**Comment by vishesh** [comment] 2017-08-29 03:09
> It would probably be possible to do automatically based on contract / type checking?

Since its dynamically typed, you can never be sure about anything. However, we already know which function applications are FFI calls, so maybe we can look for certain pattern around that. 

`htdp/image`, `htdp/universe` and Playground is probably broken too as they make heavy use of FFI.

**Comment by glebm** [comment] 2017-08-29 08:50
A concrete proposal for this issue (non-automatic conversion):

```
($/string "Hello World") ;;=> "Hello World"
($/string variable) ;;=> variable.toString()
```

I have no idea how to implement this, but hopefully it won't be too difficult for you.

**Comment by vishesh** [comment] 2017-08-29 08:55
Yeah that's a quick fix. I can do it if you need it for now. However, will need to think a bit more on whole FFI scene, not just this.

**Comment by glebm** [comment] 2017-08-29 09:24
Yes please, I need this one and the `$/ustring` one to get waxeye to run. Thank you :)

**Comment by vishesh** [comment] 2017-08-29 10:04
@glebm If we represent string as native string, apart from `string-append` what other Racket library functions break? I'm trying to see what other languages are doing with this. For example Elm uses this:

    https://github.com/elm-lang/core/blob/master/src/Elm/Kernel/String.js

The Elm approach seems to be using native strings, but doing some unicode business inside the library functions. I can't claim to understand what they are doing right now as I barely recall any low level details of unicode.

ClojureScript I believe does something similar, and has `count` function which returns the right thing. I'm not sure how fast/slow the standard`charCodeAt` is, but maybe we don't have to worry about worst case but the average case e.g. small strings. Using native string as exposed representation  can save lot of trouble in many other ways (runtime, compiler, ffi). Whatever direction we take, it should be based on measurements to compare it for best, average and worst cases[1]. The measurement is not just about microbenchmarks but probably also consider what kind of operations are more common than others? For example, `string-append` is probably more common than `length`.

Regarding this FFI addition I will look into it tomorrow after work. 

[1] Although with supporting bignums/exactnums we will be back to this whole FFI problem, but I think we should still take measurements to back our design decision with some evidence.

**Comment by glebm** [comment] 2017-08-29 10:40
>  I'm trying to see what other languages are doing with this.

Elm Strings are not Unicode strings:

![elm](https://user-images.githubusercontent.com/216339/29816815-90644322-8cad-11e7-9233-50d3547c2876.png)

ClojureScript are not Unicode strings either. The `count` function is `O(n)`.

These languages can get away with non-Unicode strings because they don't have to be compatible with something else (Elm is its own language, and ClojureScript compiles to either JavaScript or the JVM which uses UTF-16 Strings just like JavaScript).

> If we represent string as native string, apart from string-append what other Racket library functions break?

`string-append` doesn't break. What breaks is any function that has to do with indices and single characters, notably `string-ref`, `string-length`.

> The measurement is not just about microbenchmarks but probably also consider what kind of operations are more common than others

It's not about the constant factor. With native strings, all the functions such as `string-ref` and `string-length` would become `O(n)` instead of `O(1)`.

**Comment by vishesh** [comment] 2017-08-29 18:28
My understanding is that they are unicode. They are UTF-16 encoded, so it would be wrong to say they are not unicode strings. The problem is that some functions treat them as bytes not as sequence of codepoints. (That unicode business there is probably doing that right in ClojureScript and Elm?).

> These languages can get away with non-Unicode strings because they don't have to be compatible with something else: Elm is its own language, and ClojureScript compiles to either JavaScript or the JVM which uses UTF-16 Strings just like JavaScript.

RacketScript doesn't aim to completely preserve the semantics of Racket. We have already ditched continuations. String semantics are obviously more important.

> string-append doesn't break (except mutability). What breaks is any function that has to do with indices and single characters, notably string-ref (may return a wrong character or a part of a surrogate pair, i.e. not a codepoint / Racket char at all), string-length (may return wrong result), etc.

Yes that's what I gathered. This along with next point is why I proposed if its possible to use native representation. 

> It's not about the constant factor. With native strings, all the functions such as string-ref and string-length would become O(n) instead of O(1).

That's why I said we should consider all best, average and worst cases. I understand they will become `O(n)`, but the point I'm making is maybe that's not a problem for most usecases. If we are paying some extra cost for 90% of cases and O(1) for 10% of cases, then probably it is probably worth a second look. For example just creating a string and passing it to external function has O(n) cost  even when we don't need it (first we try to split it into codepoints, then join them. Maybe we can optimize by lazily getting codepoints than always splitting them off).

I'm not claiming anything, but just suggesting that its worth looking into few things before we make conclusions. These are some points that I can recall from my experience reading and writing Racket code.

1. Which string operations are more common? I don't think `string-ref` is used very often. `string-set!` are even more uncommon. On other hand `string-prefix?`, `substring`, `reverse` and `string-replace` are much more common IMO.
2. If you iterating through all characters, good Racket programs are likely to use `string->list` or `in-string` rather then `string-ref`. Which means, the you are doing same amount work as your UnicodeClass.
3. Most strings are not big strings. I'm not a full-time web development guy, but I think its particularly true in this domain. Decoding small strings each time wont be a huge bottleneck in that case. 
4. Mutability is still a problem and can't be fixed by any other approach than we have. However, I think they are rarely mutated. We can just choose to not support `string-ref!`.

To validate all these we should look at various kinds of real programs (big-bang, waxye, typical web app ...) and see how they perform. Microbenchmark will give us some idea, but they don't tell us what kind of workload we will generally get.

Overall the point is that to cover a small subset of worst case, do we want to add extra cost to average case. And even if we are slightly worse off (by small factor) on average, is it worthwhile to support mutable strings and best worst-case complexity at expense of much more verbose and inconvenient FFI.

**Comment by glebm** [comment] 2017-08-29 18:42
> My understanding is that they are unicode. They are UTF-16 encoded, so it would be wrong to say they are not unicode strings.

Sure, that's what I meant. Unicode codepoints vs code units in an encoding.
Being pedantic, though, they are not Unicode. It is possible to have a String object that does not correspond to a Unicode string (`"\ud800a"`).

Overall, I agree that it's important to measure. In the absence of measurement I've optimized for my use case.

I think web development with RacketScript is never going to happen at scale. Racket itself is a fringe language, it requires bundling a runtime, it's not usually typed, etc.

I see RacketScript as primarily a tool for running existing Racket code in the browser. For this reason, I'm not concerned much with external functions, especially because:

> Maybe we can optimize by lazily getting codepoints than always splitting them off

It is certainly possible and fits well within the current design (just needs a couple more subclasses for AbstractUString with lazy `get chars` and a `constructor(chars: Char[]|null, s: String)`.

**Comment by vishesh** [comment] 2017-08-30 03:58
> It is possible to have a String object that does not correspond to a Unicode string ("\ud800a")

Is it just for `0xd800`-`0xd8ff` range or there are other examples? From UTF8 wiki it seems that this range should not be encoded at first place (sounds like undefined behavior if implementations do that).  Correct me if I'm wrong here but does ES6 fix that? 

```
> "\u{d800a}" == "\ud800a"
false
> "\u{d800a}".codePointAt(0) == "\ud800a".codePointAt(0)
false
> "\u{d800a}".codePointAt(0) === "\ud800a".codePointAt(0)
false
> String.fromCodePoint("\u{d800a}".codePointAt(0)) === String.fromCodePoint("\ud800a".codePointAt(0))
false
> String.fromCodePoint("\u{d800a}".codePointAt(0)) === "\ud800a"
false
> String.fromCodePoint("\u{d800a}".codePointAt(0)) === "\u{d800a}"
true
```

> Racket itself is a fringe language, it requires bundling a runtime, it's not usually typed, etc.

Static vs Dynamic typing is a classic debate, but I believe that there is place for both in this world (including web). Huge run-times are undesirable, but we can try to make it smaller and more efficient with time from both compiler and raw JS code perspective.

> I think web development with RacketScript is never going to happen at scale. [...] I see RacketScript as primarily a tool for running existing Racket code in the browser. For this reason, I'm not concerned much with external functions.

If you mean scale in terms of popularity, then that is not a concern for now. If you mean scale as project grows, that definitely is, something we want to address by:

1. Building better tooling, more powerful compiler and optimized run-time.
2. An easy to use and (hopefully) safe FFI.
3. From language design perspective, we are implementing Racket from which we an leverage  `#lang`  system, its reader and macro expander.
4. Not supporting some Racket features which are expensive to implement in JS. e.g. continuations.
5. Implementing some useful examples to prove our point.

Of-course there are people who just want to run existing Racket programs, and there is Whalesong for that which does an excellent job implementing some of the trickiest features of Racket (sadly not actively maintained). RacketScript's wants to be more than a "demo in browser" port of Racket, and for that to happen good FFI is absolutely necessary.

**Comment by glebm** [comment] 2017-08-30 08:29
> Is it just for 0xd800-0xd8ff range or there are other examples? From UTF8 wiki it seems that this range should not be encoded at first place (sounds like undefined behavior if implementations do that).

This is not UTF-8. This is a surrogate pair range that is used in UTF-16. They should always come in pairs for a String to be valid Unicode but a `String` being valid Unicode is not required in JavaScript.

> Correct me if I'm wrong here but does ES6 fix that?

No, in my example, the byte escape is `\ud800` followed by a literal `a`.
Anyway this is just a pedantic point with no literal implications.

> If you mean scale in terms of popularity, then that is not a concern for now.

Popularity / use by websites that care about client-side performance.
Agree with the rest.

> Of-course there are people who just want to run existing Racket programs, and there is Whalesong [...]

Not only it's no longer maintained, it also doesn't support newer versions of Racket, so we can't use it for the Waxeye demo / web IDE.

---

There are two action items that I've identified in this discussion and opened separate tickets about:

1. Benchmarks #85 
2. Lazy `chars` #89

**Comment by vishesh** [comment] 2017-08-30 08:53
> Anyway this is just a pedantic point with no literal implications.

So in a right implementation this should be an error, but JavaScript just accepts that? Anyway, I guess I can ignore the details and basically come to point of implications. What cases we'll stray from, and what (is it only thing?) and is it worth the trouble caused otherwise in terms of FFI and not using native representation (and implementing library functions properly).

**Comment by glebm** [comment] 2017-08-30 09:02
>  is it worth the trouble caused otherwise in terms of FFI

I believe so. Racket is used a lot for parsing code, and `string-ref` and the like are super useful there. Not everything is easily doable with character iteration, often you do need indices.

Especially assuming it is possible to automatically pass JavaScript strings to JavaScript functions and Racket strings to Racket functions, and implementing the lazy optimization.

**Comment by vishesh** [comment] 2017-08-30 09:48
I think my previous comments covers this. Overall, there is no clear answer until we get some measurements on this. Just to add I did quick search on `string-ref` in standard library, parsack, megaparsec, match-string, sweet-exp, remix, scribble and drracket and here are my quick takes:

1. `string-set!` is almost never used.
2. `string-ref` is not uncommon, but a lot of use-case is around getting first character. There are some instances of `string-ref` for last character. 
3. Here are few instances of it being used in standard library within a loop. Most notably, it is used in `string-prefix?`, `string-suffix?` and `string-contains?` which I so far assumed to be kernel primitives. Turns out they are part of `racket/string`.
4. And lastly, for loop with `in-string` expands to a loop using `string-ref` which is more troubling if we want to use native string as that is idiomatic Racket way to iterate through strings.

So, (3) and (4) in particular are very strong reasons to stay with non-native representation[1].

[1] At-least until we are rely on original Racket library. I've also considered having our own small library (or at-least ability to override specific ones), as stdlib uses some primitives and forms that are simply not feasible or too hacky for us to implement.

**Closed** 2017-09-02 05:13 UTC
Labels: discussion, enhancement
